name: Server CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        working-directory: server
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        working-directory: server
        run: |
          poetry config settings.virtualenvs.in-project false
          poetry config settings.virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        working-directory: server
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Quality
        working-directory: server
        run: poetry run black . --check

      - name: Test with pytest
        working-directory: server
        env:
          DJANGO_SETTINGS_MODULE: project.settings
          SECRETS_FILE: .confidential/ci.json
        run: ./ci.sh
